const List<String> drugs = [
  'Accupril',
  'Aciphex',
  'Actos',
  'Adderall',
  'Allegra',
  'Allegra-D',
  'Allopurinol',
  'Alphagan',
  'Alprazolam',
  'Altace',
  'Amaryl',
  'Ambien',
  'Amitriptyline HCL',
  'Amphetamine',
  'Aricept',
  'Atenolol',
  'Atrovent',
  'Augmentin',
  'Avapro',
  'Cardura',
  'Carisoprodol',
  'Celebrex',
  'Celexa',
  'Cipro',
  'Claritin',
  'Climara',
  'Clonazepam',
  'Clonidine',
  'Combivent',
  'Coumadin',
  'Cozaar',
  'Cyclobenzaprine',
  'Depakote',
  'Detrol',
  'Diazepam',
  'Diflucan',
  'Dilantin',
  'Diovan',
  'Diovan HCT',
  'Flonase',
  'Flovent',
  'Folic Acid',
  'Furosemide',
  'Gemfibrozil',
  'Glyburide',
  'Hydrocodone',
  'Hyzaar',
  'Ibuprofen',
  'Imitrex',
  'Isosorbide Mononitrate',
  'Lanoxin',
  'Lescol',
  'Levoxyl',
  'Lipitor',
  'Lorazepam',
  'Lotensin',
  'Lotrel',
  'Macrobid',
  'Medroxyprogesterone',
  'Methamphetamine',
  'Methylphenidate',
  'Methylprednisolone',
  'Metoprolol Tartrate',
  'Miacalcin',
  'Naproxen',
  'Naproxen Sodium',
  'Nasonex',
  'Neurontin',
  'Norvasc',
  'Oxcarbazepine',
  'Oxycodone',
  'OxyContin',
  'Paxil',
  'Pepcid',
  'Phenergan',
  'Plavix',
  'Potassium Chloride',
  'Prednisone',
  'Premarin',
  'Prevacid',
  'Prilosec',
  'Promethazine',
  'Proventil HFA',
  'Prozac',
  'Relafen',
  'Risperdal',
  'Ritalin',
  'Serevent',
  'Singulair',
  'Synthroid',
  'Tamoxifen Citrate',
  'Temazepam',
  'Tiazac',
  'Tobradex',
  'Ultram',
  'Valtrex',
  'Vasotec',
  'Verapamil',
  'Viagra',
  'Warfarin Sodium',
  'Xalatan',
  'Zestoretic',
  'Zestril',
  'Ziac',
  'Zithromax',
  'Zocor',
  'Zoloft',
  'Zyprexa',
  'Zyrtec'
];
const List<String> heart = [
'Accupril',
'Altace',
'Atenolol',
'Avapro',
'Cozaar',
  'Cardura',
  'Clonidine',
  'Coumadin',
  'Diovan',
  'Diovan HCT',
  'Furosemide',
  'Gemfibrozil',
  'Hyzaar',
  'Isosorbide Mononitrate',
  'Lanoxin',
  'Lescol',
  'Lipitor',
  'Lotensin',
  'Lotrel',
  'Metoprolol Tartrate',
  'Miacalcin',
  'Norvasc',
  'Plavix',
  'Tiazac',
  'Vasotec',
  'Verapamil',
  'Warfarin Sodium',
  'Zestoretic',
  'Zestril',
  'Ziac',
  'Zocor'
];
const List<String> stomach =[
  'Aciphex',
  'Pepcid',
  'Potassium Chloride',
  'Prednisone',
  'Prevacid',
  'Prilosec'];
const List<String> diabetes =[
  "Actos","Amaryl","Glyburide"];
const List<String> stimulants =[
  "Adderall",
  "Amaryl", 
  'Amphetamine',
  'Methamphetamine',
  'Methylphenidate',
  'Ritalin'];
const List<String> antinflammatory =[ 
  'Allegra',
  'Allegra-D',
  'Celebrex',
  'Claritin',
  'Flonase',
  'Flovent',
  'Methylprednisolone',
  'Naproxen',
  'Naproxen Sodium',
  'Promethazine',
  'Relafen',
  'Singulair',
  'Zyrtec'];
const List<String> antidepressants =[ 
    'Alprazolam',
  'Amitriptyline HCL',
  'Celexa',
  'Clonazepam',
  'Diazepam',
  'Paxil',
  'Prozac',
  'Zoloft'];
const List<String> sleepDisorder =[
  'Ambien',
  'Lorazepam',
  'Phenergan',
  'Temazepam'];
const List<String> antibiotec =[ 
  'Augmentin',
  'Cipro',
  'Diflucan',
  'Macrobid',
  'Zithromax'];
const List<String> painKiller =[ 
   'Carisoprodol',
  'Cyclobenzaprine',
  'Hydrocodone',
  'Ibuprofen',
  'Oxycodone',
  'OxyContin',
  'Ultram'];
const List<String> seizure =[ 
    'Depakote',
  'Dilantin',
  'Imitrex',
  'Neurontin',
  'Oxcarbazepine'];
const List<String> hormons =[  
  'Levoxyl',
  'Premarin',
  'Synthroid',
  'Climara',
  'Medroxyprogesterone'];
const List<String> eye =[
  "Alphagan","Tobradex","Xalatan"];
const List<String> lungs =[
  "Atrovent","Combivent",'Proventil HFA',"Serevent"];
const List<String> others =[ 
  'Aricept',
  'Allopurinol',
  'Folic Acid',
  'Detrol',
  'Tamoxifen Citrate',
  'Valtrex',
  'Nasonex',
  'Risperdal',
  'Viagra',
  'Zyprexa'];
